import type { CopsoqPergunta } from "@/lib/copsoq/types";

const FOLLOW_UP_FONTES = {
  texto: "Se sim, de quem? (Você pode assinalar mais de uma opção)",
  tipoEscala: "fonte_exposicao" as const,
  multiplaEscolha: true,
  exibirQuandoRespostaDiferenteDe: "Não",
};

/**
 * 40 perguntas avaliativas oficiais do Formulário COPSOQ II-Br.
 * Textos idênticos ao PDF — não alterar.
 */
export const COPSOQ_PERGUNTAS: readonly CopsoqPergunta[] = [
  {
    id: "p-1a",
    codigo: "1A",
    questaoPrincipal: 1,
    dimensaoId: "demandas-trabalho",
    texto: "Você atrasa a entrega do seu trabalho?",
    tipoEscala: "frequencia",
    ordem: 1,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-1b",
    codigo: "1B",
    questaoPrincipal: 1,
    dimensaoId: "demandas-trabalho",
    texto: "O tempo para realizar as suas tarefas no trabalho é suficiente?",
    tipoEscala: "frequencia",
    ordem: 2,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: true,
  },
  {
    id: "p-2a",
    codigo: "2A",
    questaoPrincipal: 2,
    dimensaoId: "demandas-trabalho",
    texto: "É necessário manter um ritmo acelerado no trabalho?",
    tipoEscala: "frequencia",
    ordem: 3,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-2b",
    codigo: "2B",
    questaoPrincipal: 2,
    dimensaoId: "demandas-trabalho",
    texto: "Você trabalha em ritmo acelerado ao longo de toda jornada?",
    tipoEscala: "frequencia",
    ordem: 4,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-3a",
    codigo: "3A",
    questaoPrincipal: 3,
    dimensaoId: "demandas-trabalho",
    texto: "Seu trabalho coloca você em situações emocionalmente desgastantes?",
    tipoEscala: "frequencia",
    ordem: 5,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-3b",
    codigo: "3B",
    questaoPrincipal: 3,
    dimensaoId: "demandas-trabalho",
    texto:
      "Você tem que lidar com os problemas pessoais de outras pessoas como parte do seu trabalho?",
    tipoEscala: "frequencia",
    ordem: 6,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },

  {
    id: "p-4a",
    codigo: "4A",
    questaoPrincipal: 4,
    dimensaoId: "influencia-desenvolvimento",
    texto: "Você tem um alto grau de influência nas decisões sobre o seu trabalho?",
    tipoEscala: "frequencia",
    ordem: 7,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-4b",
    codigo: "4B",
    questaoPrincipal: 4,
    dimensaoId: "influencia-desenvolvimento",
    texto: "Você pode interferir na quantidade de trabalho atribuída a você?",
    tipoEscala: "frequencia",
    ordem: 8,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-5a",
    codigo: "5A",
    questaoPrincipal: 5,
    dimensaoId: "influencia-desenvolvimento",
    texto: "Você tem a possibilidade de aprender coisas novas através do seu trabalho?",
    tipoEscala: "intensidade",
    ordem: 9,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-5b",
    codigo: "5B",
    questaoPrincipal: 5,
    dimensaoId: "influencia-desenvolvimento",
    texto: "Seu trabalho exige que você tome iniciativas?",
    tipoEscala: "intensidade",
    ordem: 10,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },

  {
    id: "p-6a",
    codigo: "6A",
    questaoPrincipal: 6,
    dimensaoId: "significado-comprometimento",
    texto: "Seu trabalho é significativo?",
    tipoEscala: "intensidade",
    ordem: 11,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-6b",
    codigo: "6B",
    questaoPrincipal: 6,
    dimensaoId: "significado-comprometimento",
    texto: "Você sente que o trabalho que faz é importante?",
    tipoEscala: "intensidade",
    ordem: 12,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-7a",
    codigo: "7A",
    questaoPrincipal: 7,
    dimensaoId: "significado-comprometimento",
    texto: "Você sente que o seu local de trabalho é muito importante para você?",
    tipoEscala: "intensidade",
    ordem: 13,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-7b",
    codigo: "7B",
    questaoPrincipal: 7,
    dimensaoId: "significado-comprometimento",
    texto:
      "Você recomendaria a um amigo que se candidatasse a uma vaga no seu local de trabalho?",
    tipoEscala: "intensidade",
    ordem: 14,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },

  {
    id: "p-8a",
    codigo: "8A",
    questaoPrincipal: 8,
    dimensaoId: "relacoes-interpessoais",
    texto:
      "No seu local de trabalho, você é informado antecipadamente sobre decisões importantes, mudanças ou planos para o futuro?",
    tipoEscala: "intensidade",
    ordem: 15,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-8b",
    codigo: "8B",
    questaoPrincipal: 8,
    dimensaoId: "relacoes-interpessoais",
    texto: "Você recebe toda a informação necessária para fazer bem o seu trabalho?",
    tipoEscala: "intensidade",
    ordem: 16,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-9a",
    codigo: "9A",
    questaoPrincipal: 9,
    dimensaoId: "relacoes-interpessoais",
    texto: "O seu trabalho é reconhecido e valorizado pelos seus superiores?",
    tipoEscala: "intensidade",
    ordem: 17,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-9b",
    codigo: "9B",
    questaoPrincipal: 9,
    dimensaoId: "relacoes-interpessoais",
    texto: "Você é tratado de forma justa no seu local de trabalho?",
    tipoEscala: "intensidade",
    ordem: 18,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-10a",
    codigo: "10A",
    questaoPrincipal: 10,
    dimensaoId: "relacoes-interpessoais",
    texto: "O seu trabalho tem objetivos/metas claros(as)?",
    tipoEscala: "intensidade",
    ordem: 19,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-10b",
    codigo: "10B",
    questaoPrincipal: 10,
    dimensaoId: "relacoes-interpessoais",
    texto: "Você sabe exatamente o que se espera de você no trabalho?",
    tipoEscala: "intensidade",
    ordem: 20,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },

  {
    id: "p-11a",
    codigo: "11A",
    questaoPrincipal: 11,
    dimensaoId: "lideranca",
    texto:
      "Você diria que o seu superior imediato dá alta prioridade para a satisfação com trabalho?",
    tipoEscala: "intensidade",
    ordem: 21,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-11b",
    codigo: "11B",
    questaoPrincipal: 11,
    dimensaoId: "lideranca",
    texto: "Você diria que o seu superior imediato é bom no planejamento do trabalho?",
    tipoEscala: "intensidade",
    ordem: 22,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-12a",
    codigo: "12A",
    questaoPrincipal: 12,
    dimensaoId: "lideranca",
    texto:
      "Com que frequência o seu superior imediato está disposto a ouvir os seus problemas no trabalho?",
    tipoEscala: "frequencia",
    ordem: 23,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-12b",
    codigo: "12B",
    questaoPrincipal: 12,
    dimensaoId: "lideranca",
    texto: "Com que frequência você recebe ajuda e suporte do seu superior imediato?",
    tipoEscala: "frequencia",
    ordem: 24,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },

  {
    id: "p-13",
    codigo: "13",
    questaoPrincipal: 13,
    dimensaoId: "interface-trabalho-individuo",
    texto:
      "Qual o seu nível de satisfação com o seu trabalho como um todo, considerando todos os aspectos?",
    tipoEscala: "satisfacao",
    ordem: 25,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },

  {
    id: "p-14a",
    codigo: "14A",
    questaoPrincipal: 14,
    dimensaoId: "conflitos-familia-trabalho",
    texto:
      "Você sente que o seu trabalho consome tanto sua energia que ele tem um efeito negativo na sua vida particular?",
    tipoEscala: "impacto_vida_particular",
    ordem: 26,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-14b",
    codigo: "14B",
    questaoPrincipal: 14,
    dimensaoId: "conflitos-familia-trabalho",
    texto:
      "Você sente que o seu trabalho ocupa tanto tempo que ele tem um efeito negativo na sua vida particular?",
    tipoEscala: "impacto_vida_particular",
    ordem: 27,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },

  {
    id: "p-15a",
    codigo: "15A",
    questaoPrincipal: 15,
    dimensaoId: "valores-local-trabalho",
    texto: "Você pode confiar nas informações que vêm dos seus superiores?",
    tipoEscala: "intensidade",
    ordem: 28,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-15b",
    codigo: "15B",
    questaoPrincipal: 15,
    dimensaoId: "valores-local-trabalho",
    texto: "Os seus superiores confiam que os funcionários farão bem seu trabalho?",
    tipoEscala: "intensidade",
    ordem: 29,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-16a",
    codigo: "16A",
    questaoPrincipal: 16,
    dimensaoId: "valores-local-trabalho",
    texto: "Os conflitos são resolvidos de forma justa?",
    tipoEscala: "intensidade",
    ordem: 30,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-16b",
    codigo: "16B",
    questaoPrincipal: 16,
    dimensaoId: "valores-local-trabalho",
    texto: "O trabalho é distribuído de forma justa?",
    tipoEscala: "intensidade",
    ordem: 31,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },

  {
    id: "p-17",
    codigo: "17",
    questaoPrincipal: 17,
    dimensaoId: "saude-geral",
    texto: "Em geral, você diria que a sua saúde é:",
    tipoEscala: "saude",
    ordem: 32,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },

  {
    id: "p-18a",
    codigo: "18A",
    questaoPrincipal: 18,
    dimensaoId: "burnout-estresse",
    texto: "Com que frequência você tem se sentido fisicamente esgotado?",
    tipoEscala: "frequencia",
    ordem: 33,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-18b",
    codigo: "18B",
    questaoPrincipal: 18,
    dimensaoId: "burnout-estresse",
    texto: "Com que frequência você tem se sentido emocionalmente esgotado?",
    tipoEscala: "frequencia",
    ordem: 34,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-19a",
    codigo: "19A",
    questaoPrincipal: 19,
    dimensaoId: "burnout-estresse",
    texto: "Com que frequência você tem se sentido estressado?",
    tipoEscala: "frequencia",
    ordem: 35,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },
  {
    id: "p-19b",
    codigo: "19B",
    questaoPrincipal: 19,
    dimensaoId: "burnout-estresse",
    texto: "Com que frequência você tem se sentido irritado?",
    tipoEscala: "frequencia",
    ordem: 36,
    obrigatoria: true,
    entraNoCalculo: true,
    pontuacaoInvertida: false,
  },

  {
    id: "p-20",
    codigo: "20",
    questaoPrincipal: 20,
    dimensaoId: "comportamentos-ofensivos",
    texto:
      "Você foi exposto a atenção sexual indesejada no seu local de trabalho durante os últimos 12 meses?",
    tipoEscala: "exposicao",
    ordem: 37,
    obrigatoria: true,
    entraNoCalculo: false,
    pontuacaoInvertida: false,
    followUp: { id: "p-20-fontes", ...FOLLOW_UP_FONTES },
  },
  {
    id: "p-21",
    codigo: "21",
    questaoPrincipal: 21,
    dimensaoId: "comportamentos-ofensivos",
    texto:
      "Você foi exposto a ameaças de violência no seu local de trabalho nos últimos 12 meses?",
    tipoEscala: "exposicao",
    ordem: 38,
    obrigatoria: true,
    entraNoCalculo: false,
    pontuacaoInvertida: false,
    followUp: { id: "p-21-fontes", ...FOLLOW_UP_FONTES },
  },
  {
    id: "p-22",
    codigo: "22",
    questaoPrincipal: 22,
    dimensaoId: "comportamentos-ofensivos",
    texto:
      "Você foi exposto a violência física em seu local de trabalho durante os últimos 12 meses?",
    tipoEscala: "exposicao",
    ordem: 39,
    obrigatoria: true,
    entraNoCalculo: false,
    pontuacaoInvertida: false,
    followUp: { id: "p-22-fontes", ...FOLLOW_UP_FONTES },
  },
  {
    id: "p-23",
    codigo: "23",
    questaoPrincipal: 23,
    dimensaoId: "comportamentos-ofensivos",
    texto:
      "Você foi exposto a “bullying” no seu local de trabalho nos últimos 12 meses?",
    tipoEscala: "exposicao",
    ordem: 40,
    obrigatoria: true,
    entraNoCalculo: false,
    pontuacaoInvertida: false,
    textoAjuda:
      "“Bullying” significa que uma pessoa é repetidamente exposta a tratamento desagradável ou degradante, do qual a vítima tem dificuldade para se defender.",
    followUp: { id: "p-23-fontes", ...FOLLOW_UP_FONTES },
  },
] as const;
